os: linux
dist: focal
language: bash
env:
  global:
  - tf_version=1.1.3
  - TF_HOST=app.terraform.io
  - TF_ORG=alex4108
  # TF_API_TOKEN
  - secure: gV2seX4w1X8zj7AXBp5XAGplb+hqqVyASeusE9BCXSL9UGjB8Eu2O1fx5oUCIgdTzgqAzA3O2fcMkIpo3HRXlD/pqY6wIa425t0DudHq9oTjrSLaTxjcX3Tcy9xC/8IQAwjJd4j5/00Sywgo0QIfviI5KD4PLtk3vYwkO5Wvttu4ANdQ3pIB9fG8IpX/dWscMJRKBXHAyvq0051mOeBiMu44RY1P3VcCxlBTlgcMkAOvvHtRAZ8LZjqhlTps8rb+bydbhWYwDuKjBxTFKBVFiy2f0Tt5gSGweGiS4pc6qxxjvCFfYYYts38Qpev3X0S4ousoR8nHm2wcvGr2eJ8H83aoddTvLoT65RzSkzYU4UyT+0RjR3JKgN8fFGBOAhwCXjRGLIjQWPlSrVfSOU0uwFiTC8K5uUctIXP5ow7acHt/C8XcKlpK1x3cIyiJQayHk+On4qolQy74vZn9UosHlmKBY0alVTiALBKZilnOooqch8PfkPtrKOPlb7yef5Cjl7om4f5f2pNX8i1UAA1rOlGACOoK3o9kY3JcqUROGFZa+EKRgx7rcuAhqbd4e4e2pkcfSTB+UWhJkjPiYJMa45KbDzR0JNrXYdlJpqrvKliCd7BP5RWn61htaM+Ma1hv7OTBsOvxcCu6OFmV9M+thnOtxhxrbNUSW4aa5X/oTz0=
cache: npm
script:
- export OLDPWD=$(pwd) &&
  mkdir -p /tmp/tf-install &&
  cd /tmp/tf-install && 
  wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip && 
  unzip terraform_"$tf_version"_linux_amd64.zip && 
  sudo mv terraform /usr/local/bin/ &&
  cd ${OLDPWD} && 
  rm -rf /tmp/tf-install
- pip3 install awscli
- cd terraform && bash ci.sh
