version: '3'
services:
  db:
    image: library/db
    env_file:
      - ../library-db/postgres.env
  server:
    image: library/backend
  frontend:
    image: library/frontend

# this will be a single docker compose file to bring up the entire app, start to stop.
